label rockchip-kernel-6.1.43
    kernel /Image
    fdt /rk3588.dtb
    append earlycon=uart8250,mmio32,0xfeb50000 console=ttyFIQ0 irqchip.gicv3_pseudo_nmi=0 root=PARTUUID=B921B045-1D rw rootwait rcupdate.rcu_expedited=1 rcu_nocbs=all